FROM mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-20.04

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Password123

COPY DatabaseProject/SQL_Query/addusers_dev.sql /docker-entrypoint-initdb.d/

# Create a directory for the entrypoint script
COPY entrypoint-mssql.sh /usr/src/app/entrypoint.sh

USER root
RUN chmod +x /usr/src/app/entrypoint.sh

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]