services:
  mssql:
    build: 
      context: .
      dockerfile: Dockerfile-mssql
    container_name: database-mssql
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: database-api-container
    environment:
      - MSSQL=Data Source=host.docker.internal;Database=AirportDB;User ID=adminUser;Password=exampleAdmin0;Trusted_Connection=False;Encrypt=True;TrustServerCertificate=True;
      - MongoDB=mongodb://root:example@host.docker.internal:27017/AirportDB?authSource=admin
      - Neo4jUrl=bolt://host.docker.internal:7687
      - Neo4jUser=neo4j
      - Neo4jPassword=Password123
      - DatabaseName=AirportDB
    ports:
      - "8080:8080"
    depends_on:
      - mssql
      - neo4j
      - mongo
    volumes:
      - api-data:/app

  neo4j:
    image: neo4j:latest
    container_name: database-neo4j
    environment:
      - NEO4J_AUTH=neo4j/Password123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins

  mongo:
    image: mongo:latest
    container_name: database-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mssql-data:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:
  mongo-data:
  api-data: